<div  class="card">
<div class="card card-header text-white bg-info">
	<h4>RE INGRESO</h4>
</div>	
  <div class="card-body">
    	<div id="rdo" class="widget">
		<fieldset id="clas"></fieldset>
	</div>
	<div id="consulta">
        	<form  class="formulario">
        		
            	<div class="form-group row">
        			<label for="clase" class="col-sm-2 col-form-label">DNI</label>
        		
        		<div class="col-sm-10">
        			 <input type="text" id="dni" name="dni" class="form-control" >
        		</div>
        	</div>
        	</form>		
    </div>
        
        		

        	
	</div>
	<div id="boton" align="center">
		<button id=buscar class="btn btn-info">Buscar</button>
	</div>
</div>
